checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "tests/"

build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    tests:
        override:
            -
                command: 'composer test'
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
